//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvToDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingClient
    {
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public decimal CreditLimit { get; set; }
        public int YearsAtCurrentAddress { get; set; }
        public System.Guid PolicyId { get; set; }
    }
}
